# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
  orm:
    default:
      timestampable: true
      blameable: true
      sortable: true
      softdeleteable: true
      sluggable: true
      tree: true
      translatable: true
