language: php
dist: xenial
services:
    - mysql

cache:
    directories:
        - $HOME/.composer/cache/files

sudo: false

before_script:
    - composer install
    - mysql -e 'create database fork_test'
    - mysql -u root fork_test < tests/data/test_db.sql
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - mysql -e "SET GLOBAL wait_timeout = 3600" # try to avoid mysql has gone away errors

after_script:
    - yarn test

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
    - cat var/logs/test.log

jobs:
    include:
        -   stage: code quality
            php: 7.1
            name: PHP Static Analysis Tool
            before_script:
                - mysql -e 'create database fork'
                - mysql -u root fork < tests/data/test_db.sql
                - cp app/config/parameters.yml.travis app/config/parameters.yml
                - mysql -e "SET GLOBAL wait_timeout = 3600" # try to avoid mysql has gone away errors
                - composer install
            script: bin/phpstan analyze src
            after_success: skip
        -   stage: code quality
            php: 7.1
            name: PHP Code Sniffer
            before_script: composer install
            script: bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 --ignore=src/Backend/Core/Js/ckfinder,src/Backend/Cache,src/Frontend/Cache,src/Backend/Core/Js/ckeditor --report=full "src"
            after_success: skip
        -   stage: test
            name: Functional
            php: 7.1
            script: travis_wait 30 bin/simple-phpunit --testsuite=functional --coverage-clover=coverage.clover
        -   stage: test
            name: Unit
            php: 7.1
            script: travis_wait 30 bin/simple-phpunit --testsuite=unit --coverage-clover=coverage.clover
        -   stage: test
            name: Installer
            php: 7.1
            script: travis_wait 30 bin/simple-phpunit --testsuite=installer --coverage-clover=coverage.clover

