language: php

matrix:
  include:
    - php: 7.1

script:
  - bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 --ignore=src/Backend/Core/Js/ckfinder,src/Backend/Cache,src/Frontend/Cache,src/Backend/Core/Js/ckeditor --report=full "src"
  - travis_wait 20 bin/simple-phpunit --coverage-clover=coverage.clover

before_script:
  - npm install -g bower
  - export SYMFONY_DEPRECATIONS_HELPER="disabled"
  - composer install
  - mysql -e 'create database fork_test'
  - mysql -u travis fork_test < tests/data/test_db.sql
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e "SET GLOBAL wait_timeout = 3600" # try to avoid mysql has gone away errors

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat app/logs/test.log

sudo: false
