version: '2'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.5
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "~/Sites/sumocoders/docker/mysql55:/var/lib/mysql"

  web:
    #image: sumocoders/fork-php56:latest
    #image: sumocoders/fork-php70:latest
    image: sumocoders/fork-php71:latest
    depends_on:
      - mysql
    environment:
      - FORK_ENV=prod
      - FORK_DEBUG=0
    links:
      - mysql
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh/:/var/www/.ssh:ro
