imports:
    - { resource: parameters.yml }
    - { resource: doctrine.yml }

parameters:
    translator.identity.class: Common\Language
    session.storage.php_bridge.class: Common\Core\Session\Storage\PhpBridgeSessionStorage

framework:
    secret:          %kernel.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    validation:
        enable_annotations: true
    csrf_protection: ~
    templating:
        engines: ['twig']
    session:
        handler_id: ~
        storage_id: session.storage.php_bridge

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'ForkCMSInstallerBundle' ]
    filters:
        cssrewrite: ~

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

monolog:
    handlers:
        main:
            type:  stream
            path:  %site.path_www%/app/logs/%kernel.environment%.log
            level: error
        # swift:
        #     type:       swift_mailer
        #     from_email: %fork.debug_email%
        #     to_email:   %fork.debug_email%
        #     subject:    %site.default_title% %fork.debug_message%
        #     level:      error
        #     formatter:  monolog.formatter.html
        #     content_type: text/html

swiftmailer:
    transport: "mail"

services:
    form.type.editor:
        class: Backend\Form\Type\EditorType
        tags:
          - { name: form.type, alias: editor}
    form.type.meta:
        class: Backend\Form\Type\MetaType
        arguments:
          - "@fork.repository.meta"
          - "@translator"
        tags:
          - { name: form.type, alias: meta}
    database:
        class: SpoonDatabase
        arguments:
            - %database.driver%
            - %database.host%
            - %database.user%
            - %database.password%
            - %database.name%
            - %database.port%
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
            # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
            # and caused some queries to break.
            - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")'] ]
            - [ setDebug, [ %kernel.debug% ]]
    mailer_configurator:
        class: Common\Mailer\Configurator
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
        arguments:
            - "@fork.settings"
            - "@service_container"

    cache.filesystem.adapter:
        class: League\Flysystem\Adapter\Local
        arguments:
            - %kernel.cache_dir%
    cache.filesystem.filesystem:
        class: League\Flysystem\Filesystem
        arguments:
            - "@cache.filesystem.adapter"
    cache.adapter:
        class: MatthiasMullie\Scrapbook\Adapters\Flysystem
        arguments:
            - "@cache.filesystem.filesystem"
    cache.buffer:
        class: MatthiasMullie\Scrapbook\Buffered\BufferedStore
        arguments:
            - "@cache.adapter"
    cache.pool:
        class: MatthiasMullie\Scrapbook\Psr6\Pool
        arguments:
            - "@cache.buffer"

    fork.settings:
        class: Common\ModulesSettings
        arguments:
            - "@database"
            - "@cache.pool"

    fork.response_securer:
        class: Common\EventListener\ResponseSecurer
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    templating:
        class: Frontend\Core\Engine\TwigTemplate
        arguments:
            - "@twig"
            - "@templating.name_parser"
            - "@templating.locator"
