imports:
    - { resource: parameters.yml }

framework:
    secret:          %kernel.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    templating:
        engines: ['twig']
    session:
        save_path: %kernel.root_dir%/cache/sessions

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'ForkCMSInstallerBundle' ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        # This pdo_ prefix should be cleaned up in the future, when completely moved to doctrine
        driver:   "pdo_%database.driver%"
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"
        charset:  UTF8

        # Remove when we don't have legacy tables anymore
        mapping_types:
            enum:       string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            ContentBlocks:
                type: annotation
                dir: %kernel.root_dir%/../src/Backend/Modules/ContentBlocks/Entity
                prefix: Backend\Modules\ContentBlocks\Entity
            Faq:
                type: annotation
                dir: %kernel.root_dir%/../src/Backend/Modules/Faq/Entity
                prefix: Backend\Modules\Faq\Entity

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

monolog:
    handlers:
        main:
            type:  stream
            path:  %site.path_www%/app/logs/logs.log
            level: debug

services:
    database:
        class: SpoonDatabase
        arguments:
            - %database.driver%
            - %database.host%
            - %database.user%
            - %database.password%
            - %database.name%
            - %database.port%
        calls:
            - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8' } ] ]
            - [ setDebug, [ %kernel.debug% ]]
    mailer:
        class: Common\Mailer
        arguments:
            - @database
