framework:
    profiler: { only_exceptions: false }
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true
    intercept_redirects: false

services:
    database_collector:
        class: Common\DataCollector\DatabaseDataCollector
        arguments:
            - @database
        tags:
            - { name: data_collector, template: "database_data_collector.html.twig", id: "database" }
