framework:
    profiler: { only_exceptions: false }
    router:
        resource: "%kernel.project_dir%/app/config/routing_dev.yml"

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%site.path_www%/var/logs/%kernel.environment%.log"
            level: debug
        dockerstdout:
            type: stream
            path: php://stdout
            level: debug
            formatter: monolog.full_trace_formatter
            channels: [!event]

services:
    database_collector:
        class: Common\DataCollector\DatabaseDataCollector
        arguments:
            - "@database"
        tags:
            - { name: data_collector, template: "database_data_collector.html.twig", id: "database" }

    monolog.full_trace_formatter:
        class: Monolog\Formatter\LineFormatter
        calls:
            - [includeStacktraces]
