imports:
    - { resource: base_config.yml }
    - { resource: parameters.yml }

parameters:
    fork.is_installed: true

services:
    templating:
        class: Frontend\Core\Engine\TwigTemplate
        public: true
        arguments:
            - "@twig"
            - "@templating.name_parser"
            - "@templating.locator"

    translator:
        class: Common\Language
        public: true
        arguments:
            - "@translator.selector"

    Backend\Modules\Locale\Engine\CacheBuilder:
        arguments:
            - "@database"

fos_rest:
    routing_loader:
        default_format: json
