parameters:
    database_driver:    pdo_mysql
    database_host:      localhost
    database_port:      ~
    database_name:      fork_master
    database_user:      root
    database_password:  1Vertigo
