blank_issues_enabled: false
contact_links:
    - name: ğŸ Bug Report
      url: https://github.com/forkcms/forkcms/issues/new?labels=Bug&template=Bug.md
      about: Something is broken? ğŸ”¨
    - name: ğŸ’¥ Critical Bug Report
      url: https://github.com/forkcms/forkcms/issues/new?labels=Bug&template=Critical_Bug.md
      about: Have you encountered something completely broken without workaround? ğŸ’£
    - name: âœ¨ Feature Request
      url: https://github.com/forkcms/forkcms/discussions/new?category=ideas-feature-requests
      about: You have a neat idea that should be implemented? ğŸ©
    - name: â“ Ask a Question
      url: https://github.com/forkcms/forkcms/discussions/new?category=help
      about: Have a problem that you can't figure out? ğŸ¤”  Ask the community for help
    - name: ğŸ”’ Report a Security Vulnerability
      url: https://github.com/forkcms/forkcms/security/policy
      about: Please review our security policy for more details
