imports:
  - { resource: commands.yml }
  - { resource: repositories.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\ContentBlocks\Api\ApiController: ~

    content_blocks.copy:
        class: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocale
        tags:
            - { name: fork.copy_module_to_other_locale }
