services:
    analytics.client_factory:
        class: Backend\Modules\Analytics\GoogleClient\ClientFactory
        arguments:
            - "@fork.settings"
            - "%kernel.cache_dir%"

    analytics.google_analytics_service:
        class: Google_Service_Analytics
        factory: ["@analytics.client_factory",createAnalyticsService]
    analytics.google_client:
        class: Google_Client
        factory: ["@analytics.client_factory",createClient]

    analytics.connector:
        class: Backend\Modules\Analytics\GoogleClient\Connector
        arguments:
            - "@analytics.google_analytics_service"
            - "@cache.pool"
            - "@fork.settings"
