services:
  mailmotor.handler.save_settings:
    class: Backend\Modules\Mailmotor\Domain\Settings\Command\SaveSettingsHandler
    arguments:
      - "@fork.settings"
    tags:
      - { name: command_handler, handles: Backend\Modules\Mailmotor\Domain\Settings\Command\SaveSettings }
  mailmotor.handler.subscription:
    class: Frontend\Modules\Mailmotor\Command\SubscriptionHandler
    arguments:
      - "@mailmotor.subscriber"
      - "@fork.settings"
    tags:
      - { name: command_handler, handles: Frontend\Modules\Mailmotor\Command\Subscription }
  mailmotor.handler.unsubscription:
    class: Frontend\Modules\Mailmotor\Command\UnsubscriptionHandler
    arguments:
      - "@mailmotor.subscriber"
    tags:
      - { name: command_handler, handles: Frontend\Modules\Mailmotor\Command\Unsubscription }
