services:
  mailmotor.form.settings:
    class: Backend\Modules\Mailmotor\Form\SettingsType
    arguments:
      - "@=service('service_container').getServiceIds()"
    tags:
        - {name: 'form.type'}
  mailmotor.form.subscription:
    class: Frontend\Modules\MailMotor\Form\SubscribeType
    arguments:
      - "@mailmotor.subscriber"
      - "@fork.settings"
    tags:
      - {name: 'form.type'}
  mailmotor.form.unsubscription:
    class: Frontend\Modules\MailMotor\Form\UnsubscribeType
    tags:
      - {name: 'form.type'}
